<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LMP2DSS6C13MQ2" name="testcases.TestNGTesting3" tests="1" failures="1" timestamp="2021-11-24T20:24:52 IST" time="0.010" errors="0">
  <testcase name="validateTest" time="0.010" classname="testcases.TestNGTesting3">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [gmail.com] but found [yahoo.com],
	Both should be same expected [gmail.com] but found [yahoo.com],
	Both should be same expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [gmail.com] but found [yahoo.com],
Both should be same expected [gmail.com] but found [yahoo.com],
Both should be same expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testcases.TestNGTesting3.validateTest(TestNGTesting3.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateTest -->
  <system-out>
<a href="C:\SIMS_PRI\MavenSeleniumPractices\Screenshot\error.jpg" target="_blank">Screenshot link </a> <a href="C:\SIMS_PRI\MavenSeleniumPractices\Screenshot\error.jpg" target="_blank"><img height=150 width=150 src="C:\SIMS_PRI\MavenSeleniumPractices\Screenshot\error.jpg"> </a>  </system-out>
</testsuite> <!-- testcases.TestNGTesting3 -->
